# Generated by Django 3.1.3 on 2020-11-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PfmTest',
            fields=[
                ('test_idx', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.TextField()),
                ('accord', models.TextField()),
                ('note', models.TextField()),
                ('sillage', models.IntegerField(null=True)),
                ('longevity', models.IntegerField(null=True)),
            ],
        ),
    ]
