# Generated by Django 3.1.3 on 2020-12-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfmtest',
            name='longevity',
        ),
        migrations.AddField(
            model_name='pfmtest',
            name='age',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pfmtest',
            name='sillage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
