# Generated by Django 3.1.3 on 2020-12-04 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0002_auto_20201204_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfmtest',
            name='testingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 10, 19, 9, 757217)),
        ),
    ]
