# Generated by Django 3.1.3 on 2020-12-04 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0004_auto_20201204_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfmlist',
            name='dates',
        ),
        migrations.AlterField(
            model_name='pfmtest',
            name='testingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 11, 44, 23, 277301)),
        ),
    ]
