# Generated by Django 3.1.3 on 2020-12-04 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0005_auto_20201204_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfmlist',
            name='before_avg_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pfmtest',
            name='testingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 11, 51, 2, 934545)),
        ),
    ]
