# Generated by Django 3.1.3 on 2020-12-04 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0006_auto_20201204_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfmtest',
            name='testingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 12, 21, 35, 301316)),
        ),
    ]
