# Generated by Django 3.1.3 on 2020-12-07 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0008_auto_20201204_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accords',
            fields=[
                ('acc_idx', models.AutoField(primary_key=True, serialize=False)),
                ('accord', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('arom_idx', models.AutoField(primary_key=True, serialize=False)),
                ('note_ko', models.TextField(blank=True, null=True)),
                ('note_en', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('noterename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aroma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Df',
            fields=[
                ('df_idx', models.AutoField(primary_key=True, serialize=False)),
                ('brand_kor', models.TextField(blank=True, null=True)),
                ('name_kor', models.TextField(blank=True, null=True)),
                ('accords', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('longevity_rate', models.FloatField(blank=True, null=True)),
                ('sillage_rate', models.FloatField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('rating_score', models.FloatField(blank=True, null=True)),
                ('brand_eng', models.TextField(blank=True, null=True)),
                ('name_eng', models.TextField(blank=True, null=True)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'df',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_idx', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('noterename', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notes',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='pfmtest',
            name='testingDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 7, 12, 3, 17, 395994)),
        ),
    ]
